// Turns the supplied brand SVG into a React component.
//
// Done mechanically rather than by hand: the file is ~9 KB of paths, gradients
// and filters, and one thing has to change in it. The wordmark ships as
// `fill="white"`, which is invisible on a light background, so it becomes
// `currentColor` and takes the theme's ink colour instead. The icon keeps its
// own brand green, which is the point of it.
//
// Two components come out: the full lockup, and the icon on its own for
// places too small for the wordmark.
//
// Run: node scripts/build-logo.mjs
import { readFileSync, writeFileSync } from 'node:fs'

const src = readFileSync('src/assets/logo.svg', 'utf8')

// SVG attributes React wants in camelCase. The rest of this export's
// attributes are already spelled the way JSX takes them.
const ATTRS = {
  'clip-path': 'clipPath',
  'color-interpolation-filters': 'colorInterpolationFilters',
  'flood-opacity': 'floodOpacity',
  'stop-color': 'stopColor',
  'stop-opacity': 'stopOpacity',
  'stroke-width': 'strokeWidth',
}

function toJsx(svg) {
  let out = svg.replace(/<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '')
  for (const [from, to] of Object.entries(ATTRS)) out = out.replaceAll(`${from}="`, `${to}="`)
  return out.replaceAll('fill="white"', 'fill="currentColor"').trim()
}

const body = toJsx(src)

// The wordmark is the single path the export fills white; everything before it
// is the icon. Splitting there gives the icon-only mark without a second file.
// `fill` sits at the end of the element in this export, so find the fill and
// walk back to the start of the path that carries it.
const fillAt = body.indexOf('fill="currentColor"')
if (fillAt === -1) throw new Error('wordmark fill not found; has the logo been re-exported?')
const wordmarkAt = body.lastIndexOf('<path', fillAt)
if (wordmarkAt === -1) throw new Error('wordmark path not found; has the logo been re-exported?')
const defsAt = body.indexOf('<defs>')
if (defsAt === -1) throw new Error('defs not found')

const icon = body.slice(0, wordmarkAt).trim()
const wordmark = body.slice(wordmarkAt, defsAt).trim()
const defs = body.slice(defsAt).trim()

const file = `// GENERATED by scripts/build-logo.mjs from src/assets/logo.svg. Do not edit
// by hand; edit the SVG and re-run the script.
//
// The wordmark inherits \`currentColor\` so it reads in both themes. The icon
// keeps the brand green, which is also where --color-accent comes from.

/** Icon and wordmark. Give it a height; the width follows. */
export function LogoLockup({ className, title = 'Further' }: { className?: string; title?: string }) {
  return (
    <svg viewBox="0 0 148 54" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-label={title} className={className}>
      ${icon}
      ${wordmark}
      ${defs}
    </svg>
  )
}

/** The icon on its own, for places with no room for the wordmark. */
export function LogoMark({ className, title }: { className?: string; title?: string }) {
  return (
    <svg
      viewBox="3 0 48 48"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      {...(title ? { role: 'img', 'aria-label': title } : { 'aria-hidden': true })}
      className={className}
    >
      ${icon}
      ${defs}
    </svg>
  )
}
`
writeFileSync('src/components/app/Logo.tsx', file)
console.log(`wrote src/components/app/Logo.tsx (${file.length} chars)`)
