/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GoalRouteImport } from './routes/goal'
import { Route as JourneysRouteImport } from './routes/journeys'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourceRouteImport } from './routes/source'
import { Route as WelcomeRouteImport } from './routes/welcome'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalRoute = GoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneysRoute = JourneysRouteImport.update({
  id: '/journeys',
  path: '/journeys',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goal': typeof GoalRoute
  '/journeys': typeof JourneysRoute
  '/settings': typeof SettingsRoute
  '/source': typeof SourceRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goal': typeof GoalRoute
  '/journeys': typeof JourneysRoute
  '/settings': typeof SettingsRoute
  '/source': typeof SourceRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goal': typeof GoalRoute
  '/journeys': typeof JourneysRoute
  '/settings': typeof SettingsRoute
  '/source': typeof SourceRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/goal' | '/journeys' | '/settings' | '/source' | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/goal' | '/journeys' | '/settings' | '/source' | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/goal'
    | '/journeys'
    | '/settings'
    | '/source'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoalRoute: typeof GoalRoute
  JourneysRoute: typeof JourneysRoute
  SettingsRoute: typeof SettingsRoute
  SourceRoute: typeof SourceRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal': {
      id: '/goal'
      path: '/goal'
      fullPath: '/goal'
      preLoaderRoute: typeof GoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journeys': {
      id: '/journeys'
      path: '/journeys'
      fullPath: '/journeys'
      preLoaderRoute: typeof JourneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoalRoute: GoalRoute,
  JourneysRoute: JourneysRoute,
  SettingsRoute: SettingsRoute,
  SourceRoute: SourceRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
