/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as InsurerRouteImport } from './routes/insurer'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TripsTripIdRouteImport } from './routes/trips.$tripId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const InsurerRoute = InsurerRouteImport.update({
  id: '/insurer',
  path: '/insurer',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsTripIdRoute = TripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => TripsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/insurer': typeof InsurerRoute
  '/plan': typeof PlanRoute
  '/settings': typeof SettingsRoute
  '/track': typeof TrackRoute
  '/trips': typeof TripsRouteWithChildren
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/trips/$tripId': typeof TripsTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/insurer': typeof InsurerRoute
  '/plan': typeof PlanRoute
  '/settings': typeof SettingsRoute
  '/track': typeof TrackRoute
  '/trips': typeof TripsRouteWithChildren
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/trips/$tripId': typeof TripsTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/insurer': typeof InsurerRoute
  '/plan': typeof PlanRoute
  '/settings': typeof SettingsRoute
  '/track': typeof TrackRoute
  '/trips': typeof TripsRouteWithChildren
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/trips/$tripId': typeof TripsTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/impact'
    | '/insurer'
    | '/plan'
    | '/settings'
    | '/track'
    | '/trips'
    | '/wallet'
    | '/welcome'
    | '/trips/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/impact'
    | '/insurer'
    | '/plan'
    | '/settings'
    | '/track'
    | '/trips'
    | '/wallet'
    | '/welcome'
    | '/trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/impact'
    | '/insurer'
    | '/plan'
    | '/settings'
    | '/track'
    | '/trips'
    | '/wallet'
    | '/welcome'
    | '/trips/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpactRoute: typeof ImpactRoute
  InsurerRoute: typeof InsurerRoute
  PlanRoute: typeof PlanRoute
  SettingsRoute: typeof SettingsRoute
  TrackRoute: typeof TrackRoute
  TripsRoute: typeof TripsRouteWithChildren
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurer': {
      id: '/insurer'
      path: '/insurer'
      fullPath: '/insurer'
      preLoaderRoute: typeof InsurerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$tripId': {
      id: '/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof TripsTripIdRouteImport
      parentRoute: typeof TripsRoute
    }
  }
}

interface TripsRouteChildren {
  TripsTripIdRoute: typeof TripsTripIdRoute
}

const TripsRouteChildren: TripsRouteChildren = {
  TripsTripIdRoute: TripsTripIdRoute,
}

const TripsRouteWithChildren = TripsRoute._addFileChildren(TripsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpactRoute: ImpactRoute,
  InsurerRoute: InsurerRoute,
  PlanRoute: PlanRoute,
  SettingsRoute: SettingsRoute,
  TrackRoute: TrackRoute,
  TripsRoute: TripsRouteWithChildren,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
